name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push,workflow_dispatch]
env:
  # Setting an environment variable with the value of a configuration variable
  env_runid: ${{ github.run_id }}
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo "The requested FQDN is ${{ vars.FQDN }}."
      - run: echo "The requested IP Address is ${{ vars.IPADDRESS }}."
      - run: echo "The requested Visibility is ${{ vars.VIEW }}."
      - run: echo "🔎 The RITM Number is ${{ vars.RITM }}."
      - run: echo "💡 The GitHub Run ID is ${{ github.run_id }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
